-- GENERAR VISTAS
/*
CREATE VIEW CRUCE AS

SELECT  E.NOMBRE, E.GENERO, E.EDAD, C.FECHA_COMPRA, C.ID_CURSO, C.ID_METODO_PAGO,C.PRECIO  FROM ESTUDIANTES AS E
INNER JOIN COMPRAS AS C ON (E.ID_ESTUDIANTE = C.ID_ESTUDIANTE)
*/

--DROP VIEW CRUCE


-- CONSULTAS MULTITABLAS
/*
SELECT E.ID_ESTUDIANTE, E.NOMBRE, E.APELLIDO,  COUNT(*) AS VECES,SUM(C.PRECIO) AS GASTO FROM ESTUDIANTES AS E
INNER JOIN COMPRAS AS C ON (E.ID_ESTUDIANTE = C.ID_ESTUDIANTE)
AND C.FECHA_COMPRA LIKE '2016-01%' 
GROUP BY E.ID_ESTUDIANTE,E.NOMBRE, E.APELLIDO
*/

-- CUANTAS PERSONAS HAN COMPRADO X CURSO


SELECT CURSOS.ID_CURSO, CURSOS.TITULO_CURSO,  COUNT(COMPRAS.ID_CURSO) FROM CURSOS
INNER JOIN COMPRAS ON (CURSOS.ID_CURSO = COMPRAS.ID_CURSO)
GROUP BY CURSOS.ID_CURSO, CURSOS.TITULO_CURSO, COMPRAS.ID_COMPRA

