-- SUBCONSULTAS O SUB QUERYS

SELECT * FROM ESTUDIANTES
WHERE ID_ESTUDIANTE > 3000000
AND ID_ESTUDIANTE IN
(
	SELECT ID_ESTUDIANTE FROM COMPRAS 
	WHERE ID_CURSO IN
(
		SELECT ID_CURSO FROM CURSOS WHERE ID_CURSO LIKE ('DW%')
)
)
